### PR TITLE
1 CSS property is overridden

### PR DESCRIPTION
**Pull request by akshitac8**
### Description
Overridden "background" property from "main-menu:target + .backdrop" is removed
.main-menu:target + .backdrop{ background: rgba(0,0,0,.85); }

### Fixes [#144](https://github.com/systers/systers.github.io/issues/144)
Type of Change
   - Code

### Code/Quality Assurance Only

- [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Changes made successfully run on the heroku made web application .

### Checklist:

Delete irrelevant options.

- [x] PR follows the style guidelines of this project
- [x] I have performed a self-review of the code.

Code/Quality Assurance Only
- [x] The  changes generate no new warnings

### CODE REVIEW

**Comment by AnkitKhatri55555** [comment]
Don't create a seperate PR .you can commit for review purpose

**Comment by akshitac8** [comment]
@AnkitKhatri55555  I don't understand what you meant by 

> .you can commit for review purpose

Is this PR ready to be merged or should I make any other changes?

**Comment by divyanshu-rawat** [comment]
@akshitac8 , Other maintainers will also review this PR.
So, wait till other review it.
@sara-02 can you review this 👍

**Comment by AnkitKhatri55555** [comment]
Ok .you mentioned an earlier commit with lesser no of lines.You can make all changes that you want to make,and later it can be reviewd

**Comment by akshitac8** [comment]
Thank you @simsausaurabh  for approving the changes :)

**Comment by akshitac8** [comment]
Hello,
May I know are there any further changes to be made before merging the bug.
Thank you:)

**Comment by akshitac8** [comment]
Hello, @sara-02 @Geekcoder555  I have created a new [PR](https://github.com/systers/systers.github.io/pull/165) in reference to this which is ready to merge.
Kindly review the changes :)

**Pull request closed without merging**
