### PR TITLE
Link to home page

### PR DESCRIPTION
**Pull request by LuthfiFauzi**
### Description
Make link form the logo to Home. Clickable logo
Make link menu to the other pages

Fixes # [ISSUE]
#96 Link to Home Page

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
  

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
This test tell me that need thoroughness for code the website. If there are any writing error, the command can not run well. From the website, I have fixed the command for logo link and menu so the menu and link is so clickable. The other hand, I fixed the link from href commad. 

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 
  

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by shreyateeza** [comment]
@luthfiFauzi squash your commits and update the PR template. :wink:

**Comment by LuthfiFauzi** [comment]
I have update the Fix # [ISSUE] on the PR. Thanks

**Comment by LuthfiFauzi** [comment]
@AnkitKhatri55555 yes, the issue make the logo clickable to the home page.

**Comment by divyanshu-rawat** [comment]
@LuthfiFauzi  please remove # [ISSUE] from your description as it's boilerplate.

**Comment by Tharangi** [comment]
This is fixed in the current version of http://systers.io/.

**Comment by Tharangi** [comment]
@Janiceilene , @divyanshu-rawat: Hope this can be closed.

**Comment by divyanshu-rawat** [comment]
Even it has merge conflicts.
closing ths issue.

**Pull request closed without merging**
