### PR TITLE
Fixes first timer issue section

### LINKED ISSUE #349: links to first-timers-only-issues in Newcomers are not reachable
## Description
As a user,
I should be able to go to the links of issues or usernames provided in newcomer section,
so that I can make use of the information listed.

## Mocks
screenshot from 2018-12-21 00-30-00
the iframe on clicking any link goes blank

### Update [Required]
- [ ] links to the issues are reachable 
- [ ] links to the users who posted the issue are reachable 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[10] hours

### PR DESCRIPTION
**Pull request by littleBuddhaa**
### Description
I have created an angular service which makes API request to api.github.com to solve the previous problems occurring while using the API in github.com/publiclab/community-toolbox. Now all the links are accessible and only issues are shown, no pull requests.

Fixes #349 #316 #313 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

 
fti3

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- UI is in sync with overall UI of the website

### How Has This Been Tested?
I have tested this on my machine locally 

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 
  

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by littleBuddhaa** [comment]
Thanks @sarnava1

**Comment by littleBuddhaa** [comment]
@BaaniLeen  @kanmodi  @anumehaagrawal  Please review the PR, I've added @f2015537 's suggestions too

**Comment by f2015537** [comment]
Sorry for bothering you @littleBuddhaa..but can you upload the new gif with the new behaviour?

**Comment by f2015537** [comment]
It's absolutely perfect now @littleBuddhaa !

**Comment by littleBuddhaa** [comment]
Thanks @anumehaagrawal :)

**Comment by BaaniLeen** [comment]
Nice work done @littleBuddhaa ! :)

**Pull request merged**
