### PR TITLE
Added lang="en"

### PR DESCRIPTION
**Pull request by Saichethan**
### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes # [ISSUE]

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation
  

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 
  

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Saichethan** [comment]
How about adding analytics to this page

**Comment by sara-02** [comment]
@Saichethan what are updates on this?

**Comment by Saichethan** [comment]
I saw some tried working on this and their Travis CI/CD is broken, I
checked if there is a problem with code or settings even my pull request
had same problem

**Comment by sara-02** [comment]
@Saichethan As covered in the bug #67 the travis problem is not specific to your PR. So please go ahead and make changes in the PR. We cannot hold your PR for long and not update it, else the issue will get reassigned to someone else.

**Comment by Saichethan** [comment]
I resolved issues

**Pull request closed without merging**
