### PR TITLE
Changed Social media icons to Icon Stack

### LINKED ISSUE #196: Change social icons to Icon Stacked social icons
## Description
As a contributor,
I need change social icons to stacked social icons,
so that I can have a better user experience.

## Mocks

Current Mockup : 
screen shot 2018-05-31 at 11 31 12 pm

Updated Mockup :
screen shot 2018-05-31 at 11 25 07 pm

### Update [Required]
- [ ] navbar.component.html
- [ ] navbar.component.scss

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours 

@Janiceilene @ancyp @divyanshu-rawat Can you assign me this issue?

### PR DESCRIPTION
**Pull request by BaaniLeen**
### Description
Added icon stack to social icons in navbar.

Fixes #196

### Type of Change:
**Delete irrelevant options.**

- Code
- User Interface  

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Mockups : 
screen shot 2018-06-01 at 11 41 37 am

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
  

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by ancyp** [comment]
what are the colors of icons without the css?
I feel the facebook and youtube colors need to be more pigmented.

**Comment by BaaniLeen** [comment]
@ancyp The original colour is black w/o stack and with stack, its white on top of black - like Medium.

**Comment by Janiceilene** [comment]
That isn't the current Medium icon according to their [branding guidelines](https://medium.design/logos-and-brand-guidelines-f1a01a733592).

**Comment by BaaniLeen** [comment]
@ancyp I feel we would not be able to meet the branding guidelines for YouTube logo with 2 colours, so let us close this issue. What are your views about it?

**Comment by ancyp** [comment]
@Janiceilene I think we should close this?

**Pull request closed without merging**
