### PR TITLE
program list updates for past 3 years

### LINKED ISSUE #346: Past three year's projects in Gsoc section are not shown
## Description
As a developer,
I need make sure the past year 3 years Gsoc projects are visible,
so that users can get the correct information.

## Mocks
screenshot from 2018-12-18 21-35-09

### Update [Required]
- [ ] Projects of 2015 visible
- [ ] Projects of 2016 visible 
- [ ] Projects of 2015 visible
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by littleBuddhaa**
### Description
I created an angular service which fetches details from the local json files for years 2107, 16 ,15 GSoC projects. 
I also made a new json file for Outreachy 2017 program list. I took the details from live systers.io website.
 
Fixes #346 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance

program

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
This has been tested locally and verified from systers.io the love website.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 
  

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by littleBuddhaa** [comment]
@BaaniLeen I made the changes you suggested , please review this!

**Comment by littleBuddhaa** [comment]
@BaaniLeen @anumehaagrawal the issues suggested by codacy-bot are pretty trivial. These files were already present from before, I haven't changed the indentation or the put double quotes. I've only used the files in this PR. Should I be making any changes ?

**Comment by f2015537** [comment]
@littleBuddhaa these are linting errors. Please lint the javascript files and do a force-push again.

**Comment by littleBuddhaa** [comment]
@f2015537 I checked the online linters, https://jsonlint.com/ . The file passed as a valid JSON. Can you suggest me any other tool ?

**Comment by anumehaagrawal** [comment]
@littleBuddhaa  Have your issues been resolved ?

**Comment by littleBuddhaa** [comment]
@anumehaagrawal yes, I made the changes to the PR

**Comment by littleBuddhaa** [comment]
@BaaniLeen  Please review!

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)

**Pull request closed without merging**
