### PR TITLE
Add lang="en"to the html start tag #38

### PR DESCRIPTION
**Pull request by Saichethan**
### Description
Added html lang="ën" tag to all pages except old.index.html

Fixes # [ISSUE]
#38 

- Code
- Quality Assurance
- User Interface
-
  

### Checklist:

- [x] My PR follows the style guidelines for this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Saichethan** [comment]
Added <html lang="en"> in all pages except "old.index.html"

**Comment by sara-02** [comment]
@Saichethan this is a duplicate of https://github.com/systers/systers.github.io/pull/86

**Comment by Saichethan** [comment]
screenshot 18

so, I pulled this PR

**Comment by AnkitKhatri55555** [comment]
@Saichethan ,there's already a PR for this

**Comment by sara-02** [comment]
@Saichethan The point being, why did you have to create a new PR, when there was already a PR for this?

**Comment by MeepyMay** [comment]
Duplicate PR. Closing.

**Pull request closed without merging**
