### PR TITLE
Refactor the navbar

### LINKED ISSUE #247: Refactor the navbar
## Description
As a contributor,
I need to refactor the navbar menu.

### Update [Required]
- [ ] navbar.component.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

@ancyp @bethanyr @ExactlyMay Can I work on this?

### PR DESCRIPTION
**Pull request by BaaniLeen**
### Description
Refactoring the navbar. Combined the Home and About Us page, Clubbed the FAQ and Contact Us section

Fixes #247 

### Time taken : 
1 hour + 1 hour(Resolving Merge Conflicts)

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation
  

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Ran it locally.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 
  

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by ancyp** [comment]
image
The more info should ideally come at the end right?

**Comment by BaaniLeen** [comment]
@ancyp Okay sure. Will do it right away. :)

**Comment by BaaniLeen** [comment]
@ancyp Updated. Please review. Thanks! :)

**Comment by ancyp** [comment]
I am not able to open home after clicking on other tabs. Looks like there is no route.
image
Can we file a bug/issue for this?

**Comment by BaaniLeen** [comment]
Ya, true! There is a bug. Currently Home needs to have a '' route, we can perhaps keep both 'home' as well as '' routes for the same. That should solve it hopefully (not tried it yet).
Will create an issue about this :)

**Comment by Janiceilene** [comment]
I agree that More Info should be at the end, but I don't think we need a Home button at all as long as the logo directs to the homepage. I think most people know to click the logo if they want to go back home.

**Comment by BaaniLeen** [comment]
@ancyp @Janiceilene Added the HomePage routing through the Systers Logo. :)
Please review :)

**Comment by bethanyr** [comment]
@BaaniLeen - can you resolve the merge conflicts - and then we can merge in this PR.

**Comment by BaaniLeen** [comment]
@bethanyr Done :)
Can we merge this now? :)

**Pull request merged**
