### PR TITLE
fixes #124 (added meta and og tags for better SEO)

### LINKED ISSUE #124: The  most common keywords should appear in one or more of the meta-tag-for SEO
## Description
The  most common keywords should appear in one or more of the meta-tags above. The  primary keywords should appear in the meta-tags to help identify the topic of the  webpage to search engines.

systers
projects 
code 
corps 
source 

Fix:
First of all, you must make sure that the page is using the meta-description tags.
Second, you must adjust these tags content in order to include some of the primary keywords displayed above.
## Acceptance Criteria
you must adjust these tags content in order to include some of the primary keywords displayed above

### Update [Required]
- [ ]  index.html
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] reporting-guidelines.html
- [ ] gsoc/2009.html
- [ ]  gsoc/2010.html
- [ ]  gsoc/2011.html
- [ ]  gsoc/2012.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ]  gsoc/2017.html
- [ ] RGSoC/2018.html
- [ ] Outreachy/2017.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by sarnava1**
### Description
Included meta and og tags for better SEO.
Fixes #124 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- Outreach

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sarnava1** [comment]
@ExactlyMay @bethanyr @Tharangi @BaaniLeen I have done the required changes here. Please review my PR and if it is fine then please merge it.

**Comment by anumehaagrawal** [comment]
I think we can add more keywords as such for better SEO , What say @BaaniLeen  ?

**Comment by sarnava1** [comment]
@anumehaagrawal @BaaniLeen  if you have any more such keywords then please tell me. I will be glad to add them.

**Comment by anumehaagrawal** [comment]
We can probably have :- women in computing, peace corps, outreachy, gsoc

**Pull request closed without merging**
