### PR TITLE
Added tests for http handlers

### LINKED ISSUE #321: Backend Testing Needed
## Description
As a developer,
I need to write tests for automated testing purposes,
so that I can test the app before deploying it .

### Update [Required]
- Test all the routes in the backend using a library like mocha

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by f2015537**
### Description
Created a full blown backend testing framework with supertest, mocha and expect. I have written tests to check whether all the http route handlers work as expected. All test cases are passing. Added a script in package.json for other developers to try out too!

Fixes #321 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Mocks
screenshot from 2019-01-11 18-55-15

### Checklist:
**Delete irrelevant options.**

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] Any dependent changes have been merged 
  

**Code/Quality Assurance Only**
- [X] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by sarnava1 — DISMISSED** [review]

**Comment by f2015537** [comment]
@BaaniLeen @anumehaagrawal @bethanyr @ancyp @janiceilene  review pls :)

**Comment by littleBuddhaa** [comment]
@f2015537 since the heroku link was down, @BaaniLeen  had asked me to use the local files for issue #346  so in my PR #360 since we are not using the previous service, I had deleted the functions which were not being used to avoid confusion, saveUser, deleteUser, getUser. Would these changes be conflicting to your PR ?

**Comment by f2015537** [comment]
Thanks for reviewing @sarnava1 and @littleBuddhaa . No @littleBuddhaa, I've tested the functions in the backend. I saw your PR. You had deleted the angular functions. No worries. Currently, I think the backend has not been integrated with the frontend so they are independent.

**Comment by littleBuddhaa** [comment]
@f2015537 alright! You could also include tests the github's api I guess ? I don't know much about tests, but since we are using those, maybe it could be handled too ?

**Comment by f2015537** [comment]
@littleBuddhaa we have not yet incorporated github's API so it's not needed. Will add tests for those once we incorporate the API.

**Comment by anumehaagrawal** [comment]
@f2015537  Any updates on this ?
Also please fix the merge conflicts :)

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)

**Pull request closed without merging**
