### PR TITLE
Issue#41

### PR DESCRIPTION
**Pull request by Saichethan**
### Description
Edited and corrected few flaws in index.html

Fixes # [ISSUE]
#41 
### Type of Change:

- Code
- Quality Assurance
- User Interface

  ### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by sara-02** [comment]
@Saichethan an Either I am comparing the wrong file, or your branch is not up to date with the upstream master branch. Please verify that once. Also the PR #52 is closer to issue #41, than your PR, please check as well.

**Comment by Saichethan** [comment]
I thought this was a task for newcomers to get familiar with codebase so, did I. Am I  wrong?

**Comment by Saichethan** [comment]
And in PR#52 I think there are some issues so, opened new PR

**Comment by Saichethan** [comment]
Why is my branch is having Conflicts?

**Comment by MeepyMay** [comment]
Duplicate PR. Was not assigned issue.

**Pull request closed without merging**
