### PR TITLE
Improper Indentation under systers weekly updates in contactus.

### LINKED ISSUE #120: Improper Indentation under systers weekly updates in contactus
## Description
As a user of the webpage, I would like to see Phone numbers in line with paragraph, so that it is visually pleasing to the eye.

### Update [Required]
- [ ] contactus.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

### PR DESCRIPTION
**Pull request by divyanshu-rawat**
### Description
Improper Indentation under systers weekly updates in contact us is fixed.

Fixes #120  

### Type of Change:

- Code
- User Interface
  
### How Has This Been Tested?
Verified on localhost.
For more details please find an attached snapshot of updated page tested on localhost.

screen shot 2018-03-05 at 2 32 39 pm

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
  

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@sara-02 please review this :)

**Comment by Janiceilene** [comment]
@divyanshu-rawat Did you check that the new indentation doesn't lead to any issues on all mobile versions? The live version is no longer working.

**Comment by Janiceilene** [comment]
@divyanshu-rawat Can you post a screen shot of the mobile version with the new indentation?

**Comment by divyanshu-rawat** [comment]
@Janiceilene this is how it looks in a mobile version.
screen shot 2018-04-22 at 1 36 43 pm

Although it's already been fixed by someone else in the past.
I think we can close this issue as well 👍

**Pull request closed without merging**
