### PR TITLE
Added Optimised(Compressed) Images for Footer

### PR DESCRIPTION
**Pull request by rbhatia46**
### Description
Replaced the uncompressed images with the compressed one's in order to optimize the web page's loading time.

### Fixes 
Optimised Loading time of the Website

### Type of Change:

- Quality Assurance
  
### How Has This Been Tested?
Tested on localhost

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by rbhatia46** [comment]
@sara-02  This PR improves the loading time of the webpage by optimizing the images and using compressed images wherever possible without degrading their quality. In one word if I could say, it's optimization.

**Comment by sara-02** [comment]
@rbhatia46 Is there an issue for this? I don't see any issue mentioned in the PR. We all get the point of optimization, but it would be great we we follow the issue--->PR protocol for any PR :)

**Comment by sara-02** [comment]
Also, not to undermine your efforts but this bot-PR seems to be doing optimization as well
https://github.com/systers/systers.github.io/pull/134

**Comment by AnkitKhatri55555** [comment]
@sara-02 ,I think issue is#116, @rbhatia46 ,please update your PR to include the issue that your PR solves

**Comment by AnkitKhatri55555** [comment]
@rbhatia46 , #134 also serves the same purpose as pointed out by @sara-02

**Comment by rbhatia46** [comment]
Okay @sara-02 @AnkitKhatri55555 I did not have a look at that bot PR before submitting this PR. No problem, I was just looking for the smallest thing which can maybe just give a little performance optimization.

**Comment by Janiceilene** [comment]
Closing, as this PR is a duplicate

**Pull request closed without merging**
