### PR TITLE
About Us tab made relevant- Fixes #117

### LINKED ISSUE #117: About us tab irrelevance
## Description
As a user of the website, I would prefer the links under "About us" - code of conduct and reporting guidelines to be under "Others" or in the footer like in https://ghc.anitab.org/ or as links in text under "Welcome to Systers' Open Source!" section of home page, so that  I do not find a irrelevance of the same.

### Update [Required]
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] gsoc/2009.html
- [ ] gsoc/2010.html
- [ ] gsoc/20111.html
- [ ] gsoc/2012.html
- [ ] gsoc/2013.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ] gsoc/2017.html
- [ ] index.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] Outreachy/2017.html
- [ ] reporting-guidelines.html
- [ ] RGSoC/2018.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by Vertika-Shukla**
Irrelevant links has been removed from About Us tab.

### Description
Irrelevant links under "About Us" tab has been removed. Code of Conduct and Reporting Guidelines are put into "Others" tab. 

Fixes  #117 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Code is run on browser to test it successfully.
untitled

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Vertika-Shukla** [comment]
@AnkitKhatri55555 Thanks Ankit
I intentionally removed "About Us" tab because appropriate content about Systers is already available on "Join Systers" tab

**Comment by Tharangi** [comment]
@Janiceilene @MeepyMay Are we going for this navigation change?

**Comment by ancyp** [comment]
@Vertika-Shukla looks like there are some conflicts
I'm not sure if this change was approved ...

**Comment by Janiceilene** [comment]
@Tharangi, we're not making this change in the navigation.  I'll close it.

**Pull request closed without merging**
