### PR TITLE
Added description meta tags

### LINKED ISSUE #124: The  most common keywords should appear in one or more of the meta-tag-for SEO
## Description
The  most common keywords should appear in one or more of the meta-tags above. The  primary keywords should appear in the meta-tags to help identify the topic of the  webpage to search engines.

systers
projects 
code 
corps 
source 

Fix:
First of all, you must make sure that the page is using the meta-description tags.
Second, you must adjust these tags content in order to include some of the primary keywords displayed above.
## Acceptance Criteria
you must adjust these tags content in order to include some of the primary keywords displayed above

### Update [Required]
- [ ]  index.html
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] reporting-guidelines.html
- [ ] gsoc/2009.html
- [ ]  gsoc/2010.html
- [ ]  gsoc/2011.html
- [ ]  gsoc/2012.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ]  gsoc/2017.html
- [ ] RGSoC/2018.html
- [ ] Outreachy/2017.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by Geekcoder555**
### Description
Added description meta tags which contain the most common keywords, which will eventually help identify the topic of the web page to search engine crawlers.
Fixes #124 

### Type of Change:
**Delete irrelevant options.**

- Code

  

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

  

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by ancyp** [comment]
@Geekcoder555 Build has failed. Please try to fix it.

**Comment by Geekcoder555** [comment]
Yes, I'm looking into it

**Comment by ancyp** [comment]
@Geekcoder555 any update on this?

**Comment by BaaniLeen** [comment]
@Geekcoder555 Any update on this?
@ancyp @Janiceilene @bethanyr Since we have not any reply in the last 23 days, shall we close this PR and unassign the issue?

**Comment by Geekcoder555** [comment]
@ancyp , Pardon me..I wasn't able to give much time due other
commitments.please Dont unassign the issue.

**Pull request closed without merging**
