### PR TITLE
link to thumbnail with hover effect

### LINKED ISSUE #343: providing link to contributors thumbnail and not just their name
## Description
As a developer,
I need make the entire image/thumbnail of the contributor as a link,
so that the user can know immediately more info about the contributors is provided.

## Mocks
screenshot from 2018-12-18 15-08-13
as of now, only the names are clickable 

### Update [Required]
- [ ] make the thumbnail a link
### Enhancement to Update [Optional]
- [ ] and hover effect and css

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hours

### PR DESCRIPTION
**Pull request by littleBuddhaa**
### Description
This is to improve user experience, so that the user knows instantly there is more information provided for each contributor. 
Fixes #343 

### Type of Change:
**Delete irrelevant options.**

- Code
- User Interface

  

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

contributor_gif
(gif attached)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

  

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sarnava1 — APPROVED** [review]
LGTM

**Review by anumehaagrawal — APPROVED** [review]

**Comment by bethanyr** [comment]
@BaaniLeen - do you remember if there was any UX guidelines around the thumbnails and if there should be a popup when you click on the thumbnail?

**Comment by BaaniLeen** [comment]
@bethanyr I don't think there were any guidelines around this.
However, I feel that if we make the entire thumbnail as a link which directly links to the user's github profile, as proposed in #343 along with the hover effect, it is good enough.
I feel the pop-up is not needed, and is not adding any extra information, since the name of the user is already written, and the github profile can be linked directly on clicking anywhere on the thumbnail.

**Comment by BaaniLeen** [comment]
@janiceilene @ancyp What do you think about this?

**Comment by bethanyr** [comment]
@BaaniLeen - I agree that the popup is not needed if it isn't providing additional information.

@littleBuddhaa - is there additional information that you think would be useful to provide on the popup that isn't already displayed on the page?

**Comment by littleBuddhaa** [comment]
@bethanyr it does show the slack username for most of the users at the moment. 
Since the details are hard coded for now, I don't think adding more information is feasible.

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)

**Pull request closed without merging**
