### PR TITLE
adds auto-scroll to footer links

### LINKED ISSUE #356: scroll to top when links in footer are clicked
## Description
As a developer,
I need to scroll to top when footer links are clicked for better user experience,
so that all the changed details of the page are shown to the user.

## Mocks
scroll_issue

### Update [Required]
- [ ] scroll to top when these three links in footer are clicked (refer the gif)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by littleBuddhaa**
### Description
I created a service which implements auto scroll to top of the page when the contact links in footer is clicked for better user interface. It works when ever a different route changes to  /contact route.

fix_auto_scroll

Fixes #356 

### Type of Change:
**Delete irrelevant options.**

- Quality Assurance
- User Interface

  

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tested locally on my machine.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 
  

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by littleBuddhaa** [comment]
@BaaniLeen  @anumehaagrawal  @kanmodi  @bethanyr Please review this

**Review by sarnava1 — COMMENTED** [review]
If we are not supposed to add those pages then it is okay. We can even link them to the links in https://anitab.org/ as you said. What do you think of this @isabelcosta @BaaniLeen @bethanyr?

**Comment by anumehaagrawal** [comment]
If there are empty links we can link them to https://anitab.org/, But I like the auto scroll implementation when we change routes.

**Comment by littleBuddhaa** [comment]
@anumehaagrawal all the 3  footer links change to contact route for now,could we replace them with  https://anitab.org/ footer links and add another 'Contact us' link in the footer for contact route?

**Comment by littleBuddhaa** [comment]
@anumehaagrawal  @BaaniLeen  Let me know your suggestions, I'll make the changes accordingly :)

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)

**Pull request closed without merging**
