### PR TITLE
Merged attributes

### LINKED ISSUE #69: Merging attributes of the same tag under one curly braces
## Description
The attributes of the same h1,h2 and h3 tags have been defined under different braces in the styles.css file making it difficult to find all the attributes of these tags. They all should be merged under the same braces. Make changes to all other such tags.
## Mocks
h1, h2, h3 {
  font-family: 'Cairo', sans-serif;
  margin-bottom: 0; 
}  Line 268

h1, h2, h3 {
  margin-left: 1rem;
  font-weight: normal;
} Line 289

Can be merged under one tag.

## Acceptance Criteria
All attributes of tags are defined in one place
### Update [Required]
- styles.css

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15 minutes

### PR DESCRIPTION
**Pull request by adityac8**
### Description
Merged various attributes under the same name to remove redundancy.

Fixes #69 

### Type of Change:

- Code
- Quality Assurance
- Bug fix 

### How Has This Been Tested?
The changes have no effect on the display of the website.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 
  

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by adityac8** [comment]
@Tharangi @sara-02 I have made the changes 😃

**Comment by BaaniLeen** [comment]
@adityac8 Please squash your commits.

**Comment by BaaniLeen** [comment]
@adityac8 Any progress? Here's a guide on how to squash commits : https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git.

**Comment by adityac8** [comment]
Done :) Sorry for the delay. Got stuck with some deadlines :)

**Comment by BaaniLeen** [comment]
Issue has been closed.

**Pull request closed without merging**
