### PR TITLE
Message added if there are no contributors

### LINKED ISSUE #232: Indicate no contributors found for a section through a message in the Contributors page
## Description
As a Systers Community member,
I need to see a message in Contributors page if there are no contributors for a certain category for a selected project,
so that I can have a better user experience.

## Mocks
[INSERT RELEVANT PNG FILE]
image

### Update [Required]
- [ ]contributors.component.ts
- [ ]contrib.ts

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

### PR DESCRIPTION
**Pull request by anumehaagrawal**
### Description
In this PR I have included a message to indicate the absence of contributors for a category

Fixes #232 

### Type of Change:
screenshot from 2018-07-05 16-40-33

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation
  

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
This has been tested by running this on local host

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 
  

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by anumehaagrawal** [comment]
@Tharangi  @kanmodi  Could you please review my PR ?

**Comment by Tharangi** [comment]
Could you update your PR description that #228 issue also addressed in the #233 PR other than #232?

**Comment by Tharangi** [comment]
@kanmodi: Can you review this, please?

**Comment by kanmodi** [comment]
Few UI bugs and changes are required but since the functionality is working, I'll merge it for now.

**Comment by anumehaagrawal** [comment]
@Tharangi  Ill look into that and create a new issue for the same

**Pull request merged**
