### PR TITLE
Created new branch 'beta' so there are no merge conflicts and added lang="en"to the html start tags for all HTML files in English issue #38

### PR DESCRIPTION
**Pull request by bhojaksmith**
### Description
I have inserted 'en' attribute to 'lang' property for all HTML pages in the English Language

Fixes # [ISSUE]
Fixed issue #38 

### Type of Change:
- Code
  

### Checklist:

- [ y ] My PR follows the style guidelines of this project
- [ y ] I have performed a self-review of my own code or materials
- [ y ] I have made corresponding changes to the documentation
  

**Code/Quality Assurance Only**
- [ y ] My changes generate no new warnings 
- [ n ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ n ] I have added tests that prove my fix is effective or that my feature works
- [ y ] New and existing unit tests pass locally with my changes
- [ y ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by anumehaagrawal** [comment]
Looks good  !, @BaaniLeen  Please review it as well :)

**Comment by bethanyr** [comment]
Hi @bhojaksmith - thank you for making a Pull Request for this issue. I'm not sure that this issue is still valid with the changes made to this project in moving to angular. The <html> tag is usually the root level element for a web page, and you do not have multiple <html> tags on a web page. When I pull down your branch and run the changes I am now seeing multiple <html> tags on the page, which is not valid html.

I'm going to follow up on the issue that is open and initiate a discussion to see if it is still actually a valid issue - because I think the pages are currently displaying the language="en" tag and no code changes are needed. I've attached a screenshot showing the duplicate tag that I'm seeing.

screen shot 2018-10-25 at 6 56 28 pm

**Comment by sarnava1** [comment]
@bethanyr yes you are correct. This issue is outdated. @bhojaksmith good work but you can close the PR as the issue no longer exists.

**Comment by bhojaksmith** [comment]
Ok sure will do, Glad i could help @sarnava1

**Comment by bethanyr** [comment]
Closing the pull request since we determined the issue is no longer needed - thanks for your help.

**Pull request closed without merging**
