### PR TITLE
Horizontally Align View Details Buttons on Project Page

### LINKED ISSUE #245: Horizontally align the View Details buttons on Project Page cards
## Description
As a contributor,
I need horizontally align the View Details buttons on the cards,
so that I can have a better UI experience.

## Mocks
screen shot 2018-07-17 at 5 50 19 am

### Update [Required]
- [ ] Update project.component.html and use card-footer, inside which we have the View Details button.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 minutes

@Janiceilene Can you please assign me the issue to work upon? :)

### PR DESCRIPTION
**Pull request by BaaniLeen**
### Description
As a contributor, I want to Horizontally Align View Details Buttons on Project Page for better UX

Fixes #245 

Time Taken : 0.25 hours + 0.25 hours(Merge conflicts resolved)

### Type of Change:

- Code
- Quality Assurance
  
**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Ran it locally.

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by ancyp** [comment]
Looks good!
It would be nice to make it work for all desktop browser resolutions. This is around 720*656.
image

Removing the padding in the button and the div and outside it seemed to fix it. Using Percentage values might also address this.

**Comment by Janiceilene** [comment]
It seems like at the point of @ancyp's screenshot, it would be better to move down to fewer cards per row. The information is so squished in each card that it's not really legible.

**Comment by ExactlyMay** [comment]
@BaaniLeen Please complete this PR with @ancyp and @Janiceilene's feedback.

**Comment by BaaniLeen** [comment]
Okay sure @ExactlyMay !
I somehow did not get a notification for this PR.
@ancyp @Janiceilene So shall I go ahead and have less number of cards in each row then? @ancyp Is this what you meant? :)

**Comment by bethanyr** [comment]
looks like there are merge conflicts.

**Comment by BaaniLeen** [comment]
@ancyp @bethanyr Can we merge this? :)

**Comment by bethanyr** [comment]
@BaaniLeen - after I merged in #249 - this PR has merge conflicts again - can you resolve?

**Comment by BaaniLeen** [comment]
@bethanyr Done :)

**Pull request merged**
